/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package petshotel.RegistrationPages;

import DataBase.pets_database;
import DataBase.user_database;
import java.awt.Color;
//import static petshotel.RegistrationPages.Account.demoList;


/**
 *
 * @author huawei
 */
public class UpdetPet extends javax.swing.JFrame {

    /**
     * Creates new form UpdetPet
     */
    public UpdetPet() {
        initComponents();
        getContentPane().setBackground(Color.WHITE); 
        setResizable(false);
         petsTypeList.setModel(pets_database.get_listpetsType());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        UpdetRadioButton1 = new javax.swing.JRadioButton();
        UpdetRadioButton2 = new javax.swing.JRadioButton();
        UpdetRadioButton3 = new javax.swing.JRadioButton();
        NoteTextField1 = new javax.swing.JTextField();
        CancelButton1 = new javax.swing.JButton();
        UpdetButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        petsTypeList = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(820, 500));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 255));
        jLabel1.setText("Updet My Pet");

        buttonGroup1.add(UpdetRadioButton1);
        UpdetRadioButton1.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        UpdetRadioButton1.setForeground(new java.awt.Color(51, 0, 255));
        UpdetRadioButton1.setText("less then 3 years");
        UpdetRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdetRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(UpdetRadioButton2);
        UpdetRadioButton2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        UpdetRadioButton2.setForeground(new java.awt.Color(51, 0, 255));
        UpdetRadioButton2.setText("3-5 years");

        buttonGroup1.add(UpdetRadioButton3);
        UpdetRadioButton3.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        UpdetRadioButton3.setForeground(new java.awt.Color(51, 0, 255));
        UpdetRadioButton3.setText("greater the 5 years");

        NoteTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoteTextField1ActionPerformed(evt);
            }
        });

        CancelButton1.setBackground(new java.awt.Color(255, 255, 0));
        CancelButton1.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        CancelButton1.setText("Cancel");
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });

        UpdetButton2.setBackground(new java.awt.Color(255, 255, 0));
        UpdetButton2.setFont(new java.awt.Font("Arial", 1, 19)); // NOI18N
        UpdetButton2.setText("Updet");
        UpdetButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdetButton2ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 51));

        petsTypeList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(petsTypeList);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(UpdetRadioButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(UpdetRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(UpdetRadioButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NoteTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(17, 17, 17)
                                        .addComponent(CancelButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(UpdetButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UpdetRadioButton1)
                    .addComponent(UpdetRadioButton2)
                    .addComponent(UpdetRadioButton3))
                .addGap(18, 18, 18)
                .addComponent(NoteTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 23, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UpdetButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(CancelButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoteTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoteTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoteTextField1ActionPerformed

    private void UpdetRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdetRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UpdetRadioButton1ActionPerformed
     String petsAge,petsType;
    private void UpdetButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdetButton2ActionPerformed
        
         petsAge="null" ;petsType="null";
        if(petsTypeList.isSelectionEmpty())
        jLabel2.setText("must choose a type");
        else if(petsTypeList.getSelectedValue().matches(pets_database.get_listpetsType().getElementAt(1).toString()))
         petsType="1";
        else if(petsTypeList.getSelectedValue().matches(pets_database.get_listpetsType().getElementAt(2).toString()))
          petsType="2"; 
        else if(petsTypeList.getSelectedValue().matches(pets_database.get_listpetsType().getElementAt(3).toString()))
         petsType="3";
        else if(petsTypeList.getSelectedValue().matches(pets_database.get_listpetsType().getElementAt(0).toString()))
         petsType="4";
        
        if(UpdetRadioButton1.isSelected())
            petsAge="<3";
        else if (UpdetRadioButton2.isSelected())
            petsAge="3-5";
        else if (UpdetRadioButton3.isSelected())
            petsAge=">5";
        else 
        jLabel2.setText("must choose an Age");

        
        if(petsType!="null" && petsAge!="null")
        { 
          pets_database.Update_pets(petsType, petsAge, NoteTextField1.getText());
          pets_database.SetNewPet(petsTypeList.getSelectedValue()+": "+petsAge+" years ("+NoteTextField1.getText()+")");
          pets_database.demoList.addElement(pets_database.getI()+" "+pets_database.returnNewPet());
          pets_database.demoList.remove(Account.remove);
          this.dispose();
        }
        
        
        
    }//GEN-LAST:event_UpdetButton2ActionPerformed

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButton1ActionPerformed
    
//    public String ReturnPet(){
//    return result;
//    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UpdetPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UpdetPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UpdetPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UpdetPet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UpdetPet().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton1;
    private javax.swing.JTextField NoteTextField1;
    private javax.swing.JButton UpdetButton2;
    private javax.swing.JRadioButton UpdetRadioButton1;
    private javax.swing.JRadioButton UpdetRadioButton2;
    private javax.swing.JRadioButton UpdetRadioButton3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> petsTypeList;
    // End of variables declaration//GEN-END:variables
}
